interface Ciudad {
  provincia: string;
  canton: string;
}

export const ciudades: Ciudad[] = [
  // Azuay
  { provincia: "AZUAY", canton: "CUENCA" },
  { provincia: "AZUAY", canton: "GIRÓN" },
  { provincia: "AZUAY", canton: "GUALACEO" },
  { provincia: "AZUAY", canton: "NABÓN" },
  { provincia: "AZUAY", canton: "PAUTE" },
  { provincia: "AZUAY", canton: "PUCARÁ" },
  { provincia: "AZUAY", canton: "SAN FERNANDO" },
  { provincia: "AZUAY", canton: "SANTA ISABEL" },
  { provincia: "AZUAY", canton: "SIGSIG" },
  { provincia: "AZUAY", canton: "OÑA" },
  { provincia: "AZUAY", canton: "CHORDELEG" },
  { provincia: "AZUAY", canton: "EL PAN" },
  { provincia: "AZUAY", canton: "SEVILLA DE ORO" },
  { provincia: "AZUAY", canton: "GUACHAPALA" },
  { provincia: "AZUAY", canton: "CAMILO PONCE ENRÍQUEZ" },
  // Bolívar
  { provincia: "BOLÍVAR", canton: "GUARANDA" },
  { provincia: "BOLÍVAR", canton: "CHILLANES" },
  { provincia: "BOLÍVAR", canton: "CHIMBO" },
  { provincia: "BOLÍVAR", canton: "ECHEANDÍA" },
  { provincia: "BOLÍVAR", canton: "SAN MIGUEL" },
  { provincia: "BOLÍVAR", canton: "CALUMA" },
  { provincia: "BOLÍVAR", canton: "LAS NAVES" },
  // Cañar
  { provincia: "CAÑAR", canton: "AZOGUES" },
  { provincia: "CAÑAR", canton: "BIBLIÁN" },
  { provincia: "CAÑAR", canton: "CAÑAR" },
  { provincia: "CAÑAR", canton: "LA TRONCAL" },
  { provincia: "CAÑAR", canton: "EL TAMBO" },
  { provincia: "CAÑAR", canton: "DÉLEG" },
  { provincia: "CAÑAR", canton: "SUSCAL" },
  // Carchi
  { provincia: "CARCHI", canton: "TULCÁN" },
  { provincia: "CARCHI", canton: "BOLÍVAR" },
  { provincia: "CARCHI", canton: "ESPEJO" },
  { provincia: "CARCHI", canton: "MIRA" },
  { provincia: "CARCHI", canton: "MONTÚFAR" },
  { provincia: "CARCHI", canton: "SAN PEDRO DE HUACA" },
  // Chimborazo
  { provincia: "CHIMBORAZO", canton: "RIOBAMBA" },
  { provincia: "CHIMBORAZO", canton: "ALAUSÍ" },
  { provincia: "CHIMBORAZO", canton: "COLTA" },
  { provincia: "CHIMBORAZO", canton: "CHAMBO" },
  { provincia: "CHIMBORAZO", canton: "CHUNCHI" },
  { provincia: "CHIMBORAZO", canton: "GUAMOTE" },
  { provincia: "CHIMBORAZO", canton: "GUANO" },
  { provincia: "CHIMBORAZO", canton: "PALLATANGA" },
  { provincia: "CHIMBORAZO", canton: "PENIPE" },
  { provincia: "CHIMBORAZO", canton: "CUMANDÁ" },
  // Cotopaxi
  { provincia: "COTOPAXI", canton: "LATACUNGA" },
  { provincia: "COTOPAXI", canton: "LA MANÁ" },
  { provincia: "COTOPAXI", canton: "PANGUA" },
  { provincia: "COTOPAXI", canton: "PUJILÍ" },
  { provincia: "COTOPAXI", canton: "SALCEDO" },
  { provincia: "COTOPAXI", canton: "SAQUISILÍ" },
  { provincia: "COTOPAXI", canton: "SIGCHOS" },
  // El Oro
  { provincia: "EL ORO", canton: "MACHALA" },
  { provincia: "EL ORO", canton: "ARENILLAS" },
  { provincia: "EL ORO", canton: "ATAHUALPA" },
  { provincia: "EL ORO", canton: "BALSAS" },
  { provincia: "EL ORO", canton: "CHILLA" },
  { provincia: "EL ORO", canton: "EL GUABO" },
  { provincia: "EL ORO", canton: "HUAQUILLAS" },
  { provincia: "EL ORO", canton: "MARCABELÍ" },
  { provincia: "EL ORO", canton: "PASAJE" },
  { provincia: "EL ORO", canton: "PIÑAS" },
  { provincia: "EL ORO", canton: "PORTOVELO" },
  { provincia: "EL ORO", canton: "SANTA ROSA" },
  { provincia: "EL ORO", canton: "ZARUMA" },
  { provincia: "EL ORO", canton: "LAS LAJAS" },
  // Esmeraldas
  { provincia: "ESMERALDAS", canton: "ESMERALDAS" },
  { provincia: "ESMERALDAS", canton: "ELOY ALFARO" },
  { provincia: "ESMERALDAS", canton: "MUISNE" },
  { provincia: "ESMERALDAS", canton: "QUININDÉ" },
  { provincia: "ESMERALDAS", canton: "SAN LORENZO" },
  { provincia: "ESMERALDAS", canton: "ATACAMES" },
  { provincia: "ESMERALDAS", canton: "RIOVERDE" },
  { provincia: "ESMERALDAS", canton: "LA CONCORDIA" },
  // Galápagos
  { provincia: "GALÁPAGOS", canton: "SAN CRISTÓBAL" },
  { provincia: "GALÁPAGOS", canton: "ISABELA" },
  { provincia: "GALÁPAGOS", canton: "SANTA CRUZ" },
  // Guayas
  { provincia: "GUAYAS", canton: "GUAYAQUIL" },
  { provincia: "GUAYAS", canton: "ALFREDO BAQUERIZO MORENO" },
  { provincia: "GUAYAS", canton: "BALAO" },
  { provincia: "GUAYAS", canton: "BALZAR" },
  { provincia: "GUAYAS", canton: "COLIMES" },
  { provincia: "GUAYAS", canton: "DAULE" },
  { provincia: "GUAYAS", canton: "DURÁN" },
  { provincia: "GUAYAS", canton: "EL EMPALME" },
  { provincia: "GUAYAS", canton: "EL TRIUNFO" },
  { provincia: "GUAYAS", canton: "MILAGRO" },
  { provincia: "GUAYAS", canton: "NARANJAL" },
  { provincia: "GUAYAS", canton: "NARANJITO" },
  { provincia: "GUAYAS", canton: "PALESTINA" },
  { provincia: "GUAYAS", canton: "PEDRO CARBO" },
  { provincia: "GUAYAS", canton: "SAMBORONDÓN" },
  { provincia: "GUAYAS", canton: "SANTA LUCÍA" },
  { provincia: "GUAYAS", canton: "SALITRE" },
  { provincia: "GUAYAS", canton: "SAN JACINTO DE YAGUACHI" },
  { provincia: "GUAYAS", canton: "PLAYAS" },
  { provincia: "GUAYAS", canton: "SIMÓN BOLÍVAR" },
  { provincia: "GUAYAS", canton: "CORONEL MARCELINO MARIDUEÑA" },
  { provincia: "GUAYAS", canton: "LOMAS DE SARGENTILLO" },
  { provincia: "GUAYAS", canton: "NOBOL" },
  { provincia: "GUAYAS", canton: "GENERAL ANTONIO ELIZALDE" },
  { provincia: "GUAYAS", canton: "ISIDRO AYORA" },
  // Imbabura
  { provincia: "IMBABURA", canton: "IBARRA" },
  { provincia: "IMBABURA", canton: "ANTONIO ANTE" },
  { provincia: "IMBABURA", canton: "COTACACHI" },
  { provincia: "IMBABURA", canton: "OTAVALO" },
  { provincia: "IMBABURA", canton: "PIMAMPIRO" },
  { provincia: "IMBABURA", canton: "SAN MIGUEL DE URCUQUÍ" },
  // Loja
  { provincia: "LOJA", canton: "LOJA" },
  { provincia: "LOJA", canton: "CALVAS" },
  { provincia: "LOJA", canton: "CATAMAYO" },
  { provincia: "LOJA", canton: "CELICA" },
  { provincia: "LOJA", canton: "CHAGUARPAMBA" },
  { provincia: "LOJA", canton: "ESPÍNDOLA" },
  { provincia: "LOJA", canton: "GONZANAMÁ" },
  { provincia: "LOJA", canton: "MACARÁ" },
  { provincia: "LOJA", canton: "PALTAS" },
  { provincia: "LOJA", canton: "PUYANGO" },
  { provincia: "LOJA", canton: "SARAGURO" },
  { provincia: "LOJA", canton: "SOZORANGA" },
  { provincia: "LOJA", canton: "ZAPOTILLO" },
  { provincia: "LOJA", canton: "PINDAL" },
  { provincia: "LOJA", canton: "QUILANGA" },
  { provincia: "LOJA", canton: "OLMEDO" },
  // Los Ríos
  { provincia: "LOS RÍOS", canton: "BABAHOYO" },
  { provincia: "LOS RÍOS", canton: "BABA" },
  { provincia: "LOS RÍOS", canton: "MONTALVO" },
  { provincia: "LOS RÍOS", canton: "PUEBLOVIEJO" },
  { provincia: "LOS RÍOS", canton: "QUEVEDO" },
  { provincia: "LOS RÍOS", canton: "URDANETA" },
  { provincia: "LOS RÍOS", canton: "VENTANAS" },
  { provincia: "LOS RÍOS", canton: "VINCES" },
  { provincia: "LOS RÍOS", canton: "PALENQUE" },
  { provincia: "LOS RÍOS", canton: "BUENA FÉ" },
  { provincia: "LOS RÍOS", canton: "VALENCIA" },
  { provincia: "LOS RÍOS", canton: "MOCACHE" },
  { provincia: "LOS RÍOS", canton: "QUINSALOMA" },
  // Manabí
  { provincia: "MANABÍ", canton: "PORTOVIEJO" },
  { provincia: "MANABÍ", canton: "BOLÍVAR" },
  { provincia: "MANABÍ", canton: "CHONE" },
  { provincia: "MANABÍ", canton: "EL CARMEN" },
  { provincia: "MANABÍ", canton: "FLAVIO ALFARO" },
  { provincia: "MANABÍ", canton: "JIPIJAPA" },
  { provincia: "MANABÍ", canton: "JUNÍN" },
  { provincia: "MANABÍ", canton: "MANTA" },
  { provincia: "MANABÍ", canton: "MONTECRISTI" },
  { provincia: "MANABÍ", canton: "PAJÁN" },
  { provincia: "MANABÍ", canton: "PICHINCHA" },
  { provincia: "MANABÍ", canton: "ROCAFUERTE" },
  { provincia: "MANABÍ", canton: "SANTA ANA" },
  { provincia: "MANABÍ", canton: "SUCRE" },
  { provincia: "MANABÍ", canton: "TOSAGUA" },
  { provincia: "MANABÍ", canton: "24 DE MAYO" },
  { provincia: "MANABÍ", canton: "PEDERNALES" },
  { provincia: "MANABÍ", canton: "OLMEDO" },
  { provincia: "MANABÍ", canton: "PUERTO LÓPEZ" },
  { provincia: "MANABÍ", canton: "JAMA" },
  { provincia: "MANABÍ", canton: "JARAMIJÓ" },
  { provincia: "MANABÍ", canton: "SAN VICENTE" },
  // Morona Santiago
  { provincia: "MORONA SANTIAGO", canton: "MORONA" },
  { provincia: "MORONA SANTIAGO", canton: "GUALAQUIZA" },
  { provincia: "MORONA SANTIAGO", canton: "LIMÓN INDANZA" },
  { provincia: "MORONA SANTIAGO", canton: "PALORA" },
  { provincia: "MORONA SANTIAGO", canton: "SANTIAGO" },
  { provincia: "MORONA SANTIAGO", canton: "SUCÚA" },
  { provincia: "MORONA SANTIAGO", canton: "HUAMBOYA" },
  { provincia: "MORONA SANTIAGO", canton: "SAN JUAN BOSCO" },
  { provincia: "MORONA SANTIAGO", canton: "TAISHA" },
  { provincia: "MORONA SANTIAGO", canton: "LOGROÑO" },
  { provincia: "MORONA SANTIAGO", canton: "PABLO SEXTO" },
  { provincia: "MORONA SANTIAGO", canton: "TIWINTZA" },
  // Napo
  { provincia: "NAPO", canton: "TENA" },
  { provincia: "NAPO", canton: "ARCHIDONA" },
  { provincia: "NAPO", canton: "EL CHACO" },
  { provincia: "NAPO", canton: "QUIJOS" },
  { provincia: "NAPO", canton: "CARLOS JULIO AROSEMENA TOLA" },
  // Orellana
  { provincia: "ORELLANA", canton: "FRANCISCO DE ORELLANA" },
  { provincia: "ORELLANA", canton: "AGUARICO" },
  { provincia: "ORELLANA", canton: "LA JOYA DE LOS SACHAS" },
  { provincia: "ORELLANA", canton: "LORETO" },
  // Pastaza
  { provincia: "PASTAZA", canton: "PASTAZA" },
  { provincia: "PASTAZA", canton: "MERA" },
  { provincia: "PASTAZA", canton: "SANTA CLARA" },
  { provincia: "PASTAZA", canton: "ARAJUNO" },
  // Pichincha
  { provincia: "PICHINCHA", canton: "QUITO" },
  { provincia: "PICHINCHA", canton: "CAYAMBE" },
  { provincia: "PICHINCHA", canton: "MEJÍA" },
  { provincia: "PICHINCHA", canton: "PEDRO MONCAYO" },
  { provincia: "PICHINCHA", canton: "RUMIÑAHUI" },
  { provincia: "PICHINCHA", canton: "SAN MIGUEL DE LOS BANCOS" },
  { provincia: "PICHINCHA", canton: "PEDRO VICENTE MALDONADO" },
  { provincia: "PICHINCHA", canton: "PUERTO QUITO" },
  // Santa Elena
  { provincia: "SANTA ELENA", canton: "SANTA ELENA" },
  { provincia: "SANTA ELENA", canton: "LA LIBERTAD" },
  { provincia: "SANTA ELENA", canton: "SALINAS" },
  // Santo Domingo de los Tsáchilas
  { provincia: "SANTO DOMINGO DE LOS TSÁCHILAS", canton: "SANTO DOMINGO" },
  { provincia: "SANTO DOMINGO DE LOS TSÁCHILAS", canton: "LA CONCORDIA" },
  // Sucumbíos
  { provincia: "SUCUMBÍOS", canton: "LAGO AGRIO" },
  { provincia: "SUCUMBÍOS", canton: "GONZALO PIZARRO" },
  { provincia: "SUCUMBÍOS", canton: "PUTUMAYO" },
  { provincia: "SUCUMBÍOS", canton: "SHUSHUFINDI" },
  { provincia: "SUCUMBÍOS", canton: "SUCUMBÍOS" },
  { provincia: "SUCUMBÍOS", canton: "CASCALES" },
  { provincia: "SUCUMBÍOS", canton: "CUYABENO" },
  // Tungurahua
  { provincia: "TUNGURAHUA", canton: "AMBATO" },
  { provincia: "TUNGURAHUA", canton: "BAÑOS DE AGUA SANTA" },
  { provincia: "TUNGURAHUA", canton: "CEVALLOS" },
  { provincia: "TUNGURAHUA", canton: "MOCHA" },
  { provincia: "TUNGURAHUA", canton: "PATATE" },
  { provincia: "TUNGURAHUA", canton: "QUERO" },
  { provincia: "TUNGURAHUA", canton: "SAN PEDRO DE PELILEO" },
  { provincia: "TUNGURAHUA", canton: "SANTIAGO DE PÍLLARO" },
  { provincia: "TUNGURAHUA", canton: "TISALEO" },
  // Zamora Chinchipe
  { provincia: "ZAMORA CHINCHIPE", canton: "ZAMORA" },
  { provincia: "ZAMORA CHINCHIPE", canton: "CHINCHIPE" },
  { provincia: "ZAMORA CHINCHIPE", canton: "NANGARITZA" },
  { provincia: "ZAMORA CHINCHIPE", canton: "YACUAMBI" },
  { provincia: "ZAMORA CHINCHIPE", canton: "YANTZAZA" },
  { provincia: "ZAMORA CHINCHIPE", canton: "EL PANGUI" },
  { provincia: "ZAMORA CHINCHIPE", canton: "CENTINELA DEL CÓNDOR" },
  { provincia: "ZAMORA CHINCHIPE", canton: "PALANDA" },
  { provincia: "ZAMORA CHINCHIPE", canton: "PAQUISHA" },
];

export const ecuadorDivisions = [
  {
    provincia: "AZUAY",
    cantones: [
      {
        canton: "CUENCA",
        parroquias: [
          "CUENCA",
          "BAÑOS",
          "CUMBE",
          "CHAUCHA",
          "CHECA (JIDCAY)",
          "CHIQUINTAD",
          "LLACAO",
          "MOLLETURO",
          "NULTI",
          "OCTAVIO CORDERO PALACIOS (SANTA ROSA)",
          "PACCHA",
          "QUINGEO",
          "RICAURTE",
          "SAN JOAQUIN",
          "SANTA ANA",
          "SAYAUSÍ",
          "SIDCAY",
          "SININCAY",
          "TARQUI",
          "TURI",
          "VALLE",
          "VICTORIA DEL PORTETE (IRQUIS)",
        ],
      },
      {
        canton: "GIRÓN",
        parroquias: ["GIRÓN", "ASUNCIÓN", "SAN GERARDO"],
      },
      {
        canton: "GUALACEO",
        parroquias: [
          "GUALACEO",
          "DANIEL CORDOVA TORAL (EL ORIENTE)",
          "JADÁN",
          "MARIANO MORENO",
          "REMIGIO CRESPO TORAL (GULAG)",
          "SAN JUAN",
          "ZHIDMAD",
          "LUIS CORDERO VEGA",
          "SIMÓN BOLÍVAR (CAB. EN GAÑANZOL)",
        ],
      },
    ],
  },
  {
    provincia: "PICHINCHA",
    cantones: [
      {
        canton: "QUITO",
        parroquias: ["BELISARIO QUEVEDO", "CARCELÉN", "CENTRO HISTÓRICO"],
      },
    ],
  },

  {
    provincia: "EL ORO",
    cantones: [
      {
        canton: "MACHALA",
        parroquias: ["MACHALA", "EL RETIRO"],
      },
      {
        canton: "ARENILLAS",
        parroquias: ["ARENILLAS", "CHACRAS", "PALMALES", "CARCABÓN"],
      },
      {
        canton: "ATAHUALPA",
        parroquias: [
          "PACCHA",
          "AYAPAMBA",
          "CORDONCILLO",
          "MILAGRO",
          "SAN JOSÉ",
          "SAN JUAN DE CERRO AZUL",
        ],
      },
      {
        canton: "BALSAS",
        parroquias: ["BALSAS", "BELLAMARÍA"],
      },
      {
        canton: "CHILLA",
        parroquias: ["CHILLA"],
      },
      {
        canton: "EL GUABO",
        parroquias: [
          "EL GUABO",
          "BARBONES (SUCRE)",
          "LA IBERIA",
          "TENDALES (CAB. EN PUERTO TENDALES)",
          "RÍO BONITO",
        ],
      },
      {
        canton: "HUAQUILLAS",
        parroquias: ["HUAQUILLAS"],
      },
      {
        canton: "MARCABELÍ",
        parroquias: ["MARCABELÍ", "EL INGENIO"],
      },
      {
        canton: "PASAJE",
        parroquias: [
          "PASAJE",
          "BUENAVISTA",
          "CASACAY",
          "LA PEÑA",
          "PROGRESO",
          "UZHCURRUMI",
          "CAÑAQUEMADA",
        ],
      },
      {
        canton: "PIÑAS",
        parroquias: [
          "PIÑAS",
          "CAPIRO (CAB. EN LA CAPILLA DE CAPIRO)",
          "LA BOCANA",
          "MOROMORO (CAB. EN EL VADO)",
          "PIEDRAS",
          "SAN ROQUE (AMBROSIO MALDONADO)",
          "SARACAY",
        ],
      },
      {
        canton: "PORTOVELO",
        parroquias: ["PORTOVELO", "CURTINCAPA", "MORALES", "SALATÍ"],
      },
      {
        canton: "SANTA ROSA",
        parroquias: [
          "SANTA ROSA",
          "BELLAVISTA",
          "JAMBELÍ",
          "LA AVANZADA",
          "SAN ANTONIO",
          "TORATA",
          "VICTORIA",
          "BELLAMARÍA",
        ],
      },
      {
        canton: "ZARUMA",
        parroquias: [
          "ZARUMA",
          "ABAÑÍN",
          "ARCAPAMBA",
          "GUNAZAN",
          "GUIZHAGUIÑA",
          "HUERTAS",
          "MALVAS",
          "MULUNCAY GRANDE",
          "SINSÃO",
          "SALVIAS",
        ],
      },
      {
        canton: "LAS LAJAS",
        parroquias: [
          "LA VICTORIA",
          "VALLE HERMOSO",
          "LA LIBERTAD",
          "EL PARAÍSO",
          "SAN ISIDRO",
        ],
      },
    ],
  },
];
